name: Test Suite

on: 
  workflow_call:

env:
  FOUNDRY_PROFILE: ci

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:

    name: Mainnet tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: ./.github/actions/install

      - name: Run tests
        run: forge test 
        env:
          # make fuzzing semi-deterministic to avoid noisy gas cost estimation
          # due to non-deterministic fuzzing (but still use pseudo-random fuzzing seeds)
          FOUNDRY_FUZZ_SEED: 0x${{ github.event.pull_request.base.sha || github.sha }}
          FORK: true
          KINTO_RPC_URL: ${{ secrets.KINTO_RPC_URL }}
          LEDGER_ADMIN: ${{ secrets.LEDGER_ADMIN }}