name: Test Suite

on: 
  workflow_call:

env:
  FOUNDRY_PROFILE: ci

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Compile
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with: 
          submodules: recursive
      
      - uses: ./.github/actions/install

      - name: Build contracts
        run: forge build --sizes

      - name: Check gas snapshots
        run: forge snapshot --diff

      - name: Save forge compilation cache
        uses: actions/cache/save@v3
        with:
          path: |
            cache
            out
          key: forge-${{ github.ref_name }}
  
  test:
    needs: build

    name: Test (${{ inputs.network }})
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: ./.github/actions/install

      - name: Run tests
        run: forge test
    
  coverage:
    needs:
      - test
      #- test-unit
      #- test-internal
      #- test-integration
      #- test-invariant
      # if: inputs.coverageThreshold != ''

    name: Coverage (${{ inputs.network }})
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: ./.github/actions/install

      - name: Generate LCOV report
        run: forge coverage --report lcov

      - name: Upload report to Codecov
        uses: codecov/codecov-action@v3
        with:
          directory: .
          fail_ci_if_error: true
          verbose: true

      # - name: Check coverage threshold
      #   uses: terencetcf/github-actions-lcov-minimum-coverage-checker@v1
      #   with:
      #     coverage-file: lcov.info
      #     minimum-coverage: 90